token: ""
bot_prefix: "!"
maps: ""
openai:
  api_key: "sk-..."
  org_id: "org-..."
  project_id: "proj_..."
  assistant_id: "asst_..."
  thread_id: "thrd_..." # Optional. If not provided, the bot will create a new thread and write to it.
