discord: # not changeable in runtime
  bot_prefix: '!'
  case_insensitive: true
  token: # Discord bot token
modules: # can change in runtime
  ai:
    allowed_roles:
    - # Discord role ID
    - # Discord role ID
    api_key: sk-...
    assistant_id: asst_...
    main_role: 1227291822917816402
    org_id: org-...
    project_id: proj_...
    thread_id: thread_... # Optional. If you don't have a thread ID, bot will create a new one and save it to this file.
  byond:
    host: # format "0.0.0.0"
    port:
    channel: # id channel where bot show status info
  whitelist:
    main_role: 1227291822917816402
    allowed_roles:
    - 885561160001257593 
    - 1167753949546299433
    - 1167847850969939969